
var RiveText = (() => {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  if (typeof __filename !== 'undefined') _scriptDir = _scriptDir || __filename;
  return (
function(moduleArg = {}) {

var m=moduleArg,aa,ba;m.ready=new Promise((a,b)=>{aa=a;ba=b});
m.onRuntimeInitialized=function(){var a=m.makeGlyphPath;m.makeGlyphPath=function(e,f){e=a(e,f);f=e[1];var g=m.heapViewU8(e[2],e[3]);let k=0;for(var l of g)switch(l){case 0:case 1:k++;break;case 2:k+=2;break;case 4:k+=3}return{rawPath:e[0],verbs:g,points:m.heapViewF32(f>>2,2*k)}};var b=m.shapeText;m.shapeText=function(e,f){e=b(e,f);return{rawResult:e,results:m.heapViewU8(e)}};var c=m.breakLines;m.breakLines=function(e,f,g){e=c(e,f,g);return{rawResult:e,results:m.heapViewU8(e)}};var d=m.fontFeatures;
m.fontFeatures=function(e){e=d(e);var f=m.heap(),g=new DataView(f,e),k=g.getUint32(0,!0);g=g.getUint32(4,!0);f=new DataView(f,k);k=[];for(var l=0;l<g;l++){var h=f.getUint32(4*l,!0);k.push(h)}m.deleteFontFeatures(e);return k};m.heap=function(){var e=m.wasmMemory;return e?e.buffer:m.HEAPU8.buffer};m.heapViewU8=function(e,f){var g=m.wasmMemory;return g?new Uint8Array(g.buffer,e,f):new Uint8Array(m.HEAPU8.buffer,e,f)};m.heapViewF32=function(e,f){var g=m.wasmMemory;return g?new Float32Array(g.buffer,e<<
2,f):new Float32Array(m.HEAPF32.buffer,e<<2,f)}};var ca=Object.assign({},m),da="./this.program",ea="object"==typeof window,n="function"==typeof importScripts,fa="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,t="",ha,ia,ja;
if(fa){var fs=require("fs"),ka=require("path");t=n?ka.dirname(t)+"/":__dirname+"/";ha=(a,b)=>{a=la(a)?new URL(a):ka.normalize(a);return fs.readFileSync(a,b?void 0:"utf8")};ja=a=>{a=ha(a,!0);a.buffer||(a=new Uint8Array(a));return a};ia=(a,b,c,d=!0)=>{a=la(a)?new URL(a):ka.normalize(a);fs.readFile(a,d?void 0:"utf8",(e,f)=>{e?c(e):b(d?f.buffer:f)})};!m.thisProgram&&1<process.argv.length&&(da=process.argv[1].replace(/\\/g,"/"));process.argv.slice(2);m.inspect=()=>"[Emscripten Module object]"}else if(ea||
n)n?t=self.location.href:"undefined"!=typeof document&&document.currentScript&&(t=document.currentScript.src),_scriptDir&&(t=_scriptDir),0!==t.indexOf("blob:")?t=t.substr(0,t.replace(/[?#].*/,"").lastIndexOf("/")+1):t="",ha=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},n&&(ja=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),ia=(a,b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType=
"arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var ma=console.log.bind(console),v=console.error.bind(console);Object.assign(m,ca);ca=null;"object"!=typeof WebAssembly&&na("no native wasm support detected");var A,oa=!1,B,C,D,pa,E,F,qa,ra,sa,ta;
function ua(){var a=A.buffer;m.HEAP8=B=new Int8Array(a);m.HEAP16=D=new Int16Array(a);m.HEAPU8=C=new Uint8Array(a);m.HEAPU16=pa=new Uint16Array(a);m.HEAP32=E=new Int32Array(a);m.HEAPU32=F=new Uint32Array(a);m.HEAPF32=qa=new Float32Array(a);m.HEAPF64=ta=new Float64Array(a);m.HEAP64=ra=new BigInt64Array(a);m.HEAPU64=sa=new BigUint64Array(a)}var va=[],wa=[],xa=[],ya=0,za=null,Aa=null;
function na(a){a="Aborted("+a+")";v(a);oa=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");ba(a);throw a;}var Ba=a=>a.startsWith("data:application/octet-stream;base64,"),la=a=>a.startsWith("file://"),Ca;Ca="rive_text.wasm";Ba(Ca)||(Ca=t+Ca);function Da(a){if(ja)return ja(a);throw"both async and sync fetching of the wasm failed";}
function Ea(a){if(ea||n){if("function"==typeof fetch&&!la(a))return fetch(a,{credentials:"same-origin"}).then(b=>{if(!b.ok)throw"failed to load wasm binary file at '"+a+"'";return b.arrayBuffer()}).catch(()=>Da(a));if(ia)return new Promise((b,c)=>{ia(a,d=>b(new Uint8Array(d)),c)})}return Promise.resolve().then(()=>Da(a))}function Fa(a,b,c){return Ea(a).then(d=>WebAssembly.instantiate(d,b)).then(d=>d).then(c,d=>{v(`failed to asynchronously prepare wasm: ${d}`);na(d)})}
function Ga(a,b){var c=Ca;return"function"!=typeof WebAssembly.instantiateStreaming||Ba(c)||la(c)||fa||"function"!=typeof fetch?Fa(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){v(`wasm streaming compile failed: ${e}`);v("falling back to ArrayBuffer instantiation");return Fa(c,a,b)}))}
var Ka={135752:(a,b,c,d,e)=>{if("undefined"===typeof window||void 0===(window.AudioContext||window.webkitAudioContext))return 0;if("undefined"===typeof window.Y){window.Y={ya:0};window.Y.fa={};window.Y.fa.xa=a;window.Y.fa.capture=b;window.Y.fa.Aa=c;window.Y.ra={};window.Y.ra.stopped=d;window.Y.ra.Xa=e;let f=window.Y;f.da=[];f.nb=function(g){for(var k=0;k<f.da.length;++k)if(null==f.da[k])return f.da[k]=g,k;f.da.push(g);return f.da.length-1};f.Za=function(g){for(f.da[g]=null;0<f.da.length;)if(null==
f.da[f.da.length-1])f.da.pop();else break};f.yb=function(g){for(var k=0;k<f.da.length;++k)if(f.da[k]==g)return f.Za(k)};f.ta=function(g){return f.da[g]};f.Ya=["touchend","click"];f.unlock=function(){for(var g=0;g<f.da.length;++g){var k=f.da[g];null!=k&&null!=k.ga&&k.state===f.ra.Xa&&k.ga.resume().then(()=>{Ha(k.Va)},l=>{console.error("Failed to resume audiocontext",l)})}f.Ya.map(function(l){document.removeEventListener(l,f.unlock,!0)})};f.Ya.map(function(g){document.addEventListener(g,f.unlock,!0)})}window.Y.ya+=
1;return 1},137930:()=>{"undefined"!==typeof window.Y&&(--window.Y.ya,0===window.Y.ya&&delete window.Y)},138094:()=>void 0!==navigator.mediaDevices&&void 0!==navigator.mediaDevices.getUserMedia,138198:()=>{try{var a=new (window.AudioContext||window.webkitAudioContext),b=a.sampleRate;a.close();return b}catch(c){return 0}},138369:(a,b,c,d,e,f)=>{if("undefined"===typeof window.Y)return-1;var g={},k={};a==window.Y.fa.xa&&0!=c&&(k.sampleRate=c);g.ga=new (window.AudioContext||window.webkitAudioContext)(k);
g.ga.suspend();g.state=window.Y.ra.stopped;c=0;a!=window.Y.fa.xa&&(c=b);g.oa=g.ga.createScriptProcessor(d,c,b);g.oa.onaudioprocess=function(l){if(null==g.ua||0==g.ua.length)g.ua=new Float32Array(qa.buffer,e,d*b);if(a==window.Y.fa.capture||a==window.Y.fa.Aa){for(var h=0;h<b;h+=1)for(var q=l.inputBuffer.getChannelData(h),r=g.ua,p=0;p<d;p+=1)r[p*b+h]=q[p];Ia(f,d,e)}if(a==window.Y.fa.xa||a==window.Y.fa.Aa)for(Ja(f,d,e),h=0;h<l.outputBuffer.numberOfChannels;++h)for(q=l.outputBuffer.getChannelData(h),r=
g.ua,p=0;p<d;p+=1)q[p]=r[p*b+h];else for(h=0;h<l.outputBuffer.numberOfChannels;++h)l.outputBuffer.getChannelData(h).fill(0)};a!=window.Y.fa.capture&&a!=window.Y.fa.Aa||navigator.mediaDevices.getUserMedia({audio:!0,video:!1}).then(function(l){g.za=g.ga.createMediaStreamSource(l);g.za.connect(g.oa);g.oa.connect(g.ga.destination)}).catch(function(l){console.log("Failed to get user media: "+l)});a==window.Y.fa.xa&&g.oa.connect(g.ga.destination);g.Va=f;return window.Y.nb(g)},141246:a=>window.Y.ta(a).ga.sampleRate,
141319:a=>{a=window.Y.ta(a);void 0!==a.oa&&(a.oa.onaudioprocess=function(){},a.oa.disconnect(),a.oa=void 0);void 0!==a.za&&(a.za.disconnect(),a.za=void 0);a.ga.close();a.ga=void 0;a.Va=void 0},141719:a=>{window.Y.Za(a)},141769:a=>{a=window.Y.ta(a);a.ga.resume();a.state=window.Y.ra.Xa},141908:a=>{a=window.Y.ta(a);a.ga.suspend();a.state=window.Y.ra.stopped}},La=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");
return a},Ma=a=>{var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=La(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},Na=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&=b.substr(0,b.length-1);return a+b},Oa=a=>{if("/"===a)return"/";a=Ma(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)},Pa=()=>{if("object"==typeof crypto&&"function"==typeof crypto.getRandomValues)return c=>
crypto.getRandomValues(c);if(fa)try{var a=require("crypto");if(a.randomFillSync)return c=>a.randomFillSync(c);var b=a.randomBytes;return c=>(c.set(b(c.byteLength)),c)}catch(c){}na("initRandomDevice")},Qa=a=>(Qa=Pa())(a);
function Ra(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!=typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=La(a.split("/").filter(d=>!!d),!b).join("/");return(b?"/":"")+a||"."}
var Sa="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0,G=(a,b,c)=>{var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&Sa)return Sa.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var g=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|g:(e&7)<<18|f<<12|g<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},
Ta=[],Ua=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},Va=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var k=a.charCodeAt(++f);g=65536+((g&1023)<<10)|k&1023}if(127>=g){if(c>=d)break;b[c++]=g}else{if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6}else{if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&
63}b[c++]=128|g>>6&63}b[c++]=128|g&63}}b[c]=0;return c-e},Wa=[];function Xa(a,b){Wa[a]={input:[],output:[],ma:b};Ya(a,Za)}
var Za={open(a){var b=Wa[a.node.rdev];if(!b)throw new I(43);a.tty=b;a.seekable=!1},close(a){a.tty.ma.fsync(a.tty)},fsync(a){a.tty.ma.fsync(a.tty)},read(a,b,c,d){if(!a.tty||!a.tty.ma.Ra)throw new I(60);for(var e=0,f=0;f<d;f++){try{var g=a.tty.ma.Ra(a.tty)}catch(k){throw new I(29);}if(void 0===g&&0===e)throw new I(6);if(null===g||void 0===g)break;e++;b[c+f]=g}e&&(a.node.timestamp=Date.now());return e},write(a,b,c,d){if(!a.tty||!a.tty.ma.Fa)throw new I(60);try{for(var e=0;e<d;e++)a.tty.ma.Fa(a.tty,b[c+
e])}catch(f){throw new I(29);}d&&(a.node.timestamp=Date.now());return e}},$a={Ra(){a:{if(!Ta.length){var a=null;if(fa){var b=Buffer.alloc(256),c=0,d=process.stdin.fd;try{c=fs.readSync(d,b)}catch(e){if(e.toString().includes("EOF"))c=0;else throw e;}0<c?a=b.slice(0,c).toString("utf-8"):a=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(a=window.prompt("Input: "),null!==a&&(a+="\n")):"function"==typeof readline&&(a=readline(),null!==a&&(a+="\n"));if(!a){a=null;break a}b=Array(Ua(a)+
1);a=Va(a,b,0,b.length);b.length=a;Ta=b}a=Ta.shift()}return a},Fa(a,b){null===b||10===b?(ma(G(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){a.output&&0<a.output.length&&(ma(G(a.output,0)),a.output=[])},gb(){return{rb:25856,tb:5,qb:191,sb:35387,pb:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},hb(){return 0},ib(){return[24,80]}},bb={Fa(a,b){null===b||10===b?(v(G(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){a.output&&0<a.output.length&&(v(G(a.output,
0)),a.output=[])}};function cb(a,b){var c=a.$?a.$.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.$,a.$=new Uint8Array(b),0<a.ba&&a.$.set(c.subarray(0,a.ba),0))}
var J={ia:null,la(){return J.createNode(null,"/",16895,0)},createNode(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new I(63);J.ia||(J.ia={dir:{node:{na:J.Z.na,ka:J.Z.ka,lookup:J.Z.lookup,va:J.Z.va,rename:J.Z.rename,unlink:J.Z.unlink,rmdir:J.Z.rmdir,readdir:J.Z.readdir,symlink:J.Z.symlink},stream:{qa:J.aa.qa}},file:{node:{na:J.Z.na,ka:J.Z.ka},stream:{qa:J.aa.qa,read:J.aa.read,write:J.aa.write,sa:J.aa.sa,Sa:J.aa.Sa,Ua:J.aa.Ua}},link:{node:{na:J.Z.na,ka:J.Z.ka,readlink:J.Z.readlink},stream:{}},
Ma:{node:{na:J.Z.na,ka:J.Z.ka},stream:db}});c=eb(a,b,c,d);16384===(c.mode&61440)?(c.Z=J.ia.dir.node,c.aa=J.ia.dir.stream,c.$={}):32768===(c.mode&61440)?(c.Z=J.ia.file.node,c.aa=J.ia.file.stream,c.ba=0,c.$=null):40960===(c.mode&61440)?(c.Z=J.ia.link.node,c.aa=J.ia.link.stream):8192===(c.mode&61440)&&(c.Z=J.ia.Ma.node,c.aa=J.ia.Ma.stream);c.timestamp=Date.now();a&&(a.$[b]=c,a.timestamp=c.timestamp);return c},ub(a){return a.$?a.$.subarray?a.$.subarray(0,a.ba):new Uint8Array(a.$):new Uint8Array(0)},Z:{na(a){var b=
{};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;16384===(a.mode&61440)?b.size=4096:32768===(a.mode&61440)?b.size=a.ba:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.bb=4096;b.blocks=Math.ceil(b.size/b.bb);return b},ka(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);if(void 0!==b.size&&(b=b.size,a.ba!=b))if(0==
b)a.$=null,a.ba=0;else{var c=a.$;a.$=new Uint8Array(b);c&&a.$.set(c.subarray(0,Math.min(b,a.ba)));a.ba=b}},lookup(){throw fb[44];},va(a,b,c,d){return J.createNode(a,b,c,d)},rename(a,b,c){if(16384===(a.mode&61440)){try{var d=gb(b,c)}catch(f){}if(d)for(var e in d.$)throw new I(55);}delete a.parent.$[a.name];a.parent.timestamp=Date.now();a.name=c;b.$[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},unlink(a,b){delete a.$[b];a.timestamp=Date.now()},rmdir(a,b){var c=gb(a,b),d;for(d in c.$)throw new I(55);
delete a.$[b];a.timestamp=Date.now()},readdir(a){var b=[".",".."],c;for(c of Object.keys(a.$))b.push(c);return b},symlink(a,b,c){a=J.createNode(a,b,41471,0);a.link=c;return a},readlink(a){if(40960!==(a.mode&61440))throw new I(28);return a.link}},aa:{read(a,b,c,d,e){var f=a.node.$;if(e>=a.node.ba)return 0;a=Math.min(a.node.ba-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write(a,b,c,d,e,f){b.buffer===B.buffer&&(f=!1);if(!d)return 0;a=a.node;a.timestamp=
Date.now();if(b.subarray&&(!a.$||a.$.subarray)){if(f)return a.$=b.subarray(c,c+d),a.ba=d;if(0===a.ba&&0===e)return a.$=b.slice(c,c+d),a.ba=d;if(e+d<=a.ba)return a.$.set(b.subarray(c,c+d),e),d}cb(a,e+d);if(a.$.subarray&&b.subarray)a.$.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.$[e+f]=b[c+f];a.ba=Math.max(a.ba,e+d);return d},qa(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.ba);if(0>b)throw new I(28);return b},sa(a,b,c){cb(a.node,b+c);a.node.ba=Math.max(a.node.ba,b+c)},
Sa(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new I(43);a=a.node.$;if(e&2||a.buffer!==B.buffer){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);c=!0;na();b=void 0;if(!b)throw new I(48);B.set(a,b)}else c=!1,b=a.byteOffset;return{xb:b,ha:c}},Ua(a,b,c,d){J.aa.write(a,b,0,d,c,!1);return 0}}},hb=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},ib=null,jb={},kb=[],lb=1,mb=null,nb=!0,I=null,fb={};
function K(a,b={}){a=Ra(a);if(!a)return{path:"",node:null};b=Object.assign({Pa:!0,Ia:0},b);if(8<b.Ia)throw new I(32);a=a.split("/").filter(g=>!!g);for(var c=ib,d="/",e=0;e<a.length;e++){var f=e===a.length-1;if(f&&b.parent)break;c=gb(c,a[e]);d=Ma(d+"/"+a[e]);c.wa&&(!f||f&&b.Pa)&&(c=c.wa.root);if(!f||b.Oa)for(f=0;40960===(c.mode&61440);)if(c=ob(d),d=Ra(Na(d),c),c=K(d,{Ia:b.Ia+1}).node,40<f++)throw new I(32);}return{path:d,node:c}}
function pb(a){for(var b;;){if(a===a.parent)return a=a.la.Ta,b?"/"!==a[a.length-1]?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}}function qb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%mb.length}function gb(a,b){var c;if(c=(c=rb(a,"x"))?c:a.Z.lookup?0:2)throw new I(c,a);for(c=mb[qb(a.id,b)];c;c=c.lb){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.Z.lookup(a,b)}
function eb(a,b,c,d){a=new sb(a,b,c,d);b=qb(a.parent.id,a.name);a.lb=mb[b];return mb[b]=a}function tb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function rb(a,b){if(nb)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function ub(a,b){try{return gb(a,b),20}catch(c){}return rb(a,"wx")}function vb(){for(var a=0;4096>=a;a++)if(!kb[a])return a;throw new I(33);}
function L(a){a=kb[a];if(!a)throw new I(8);return a}function wb(a,b=-1){xb||(xb=function(){this.Y={}},xb.prototype={},Object.defineProperties(xb.prototype,{object:{get(){return this.node},set(c){this.node=c}},flags:{get(){return this.Y.flags},set(c){this.Y.flags=c}},position:{get(){return this.Y.position},set(c){this.Y.position=c}}}));a=Object.assign(new xb,a);-1==b&&(b=vb());a.fd=b;return kb[b]=a}var db={open(a){a.aa=jb[a.node.rdev].aa;a.aa.open?.(a)},qa(){throw new I(70);}};
function Ya(a,b){jb[a]={aa:b}}function yb(a,b){var c="/"===b,d=!b;if(c&&ib)throw new I(10);if(!c&&!d){var e=K(b,{Pa:!1});b=e.path;e=e.node;if(e.wa)throw new I(10);if(16384!==(e.mode&61440))throw new I(54);}b={type:a,wb:{},Ta:b,kb:[]};a=a.la(b);a.la=b;b.root=a;c?ib=a:e&&(e.wa=b,e.la&&e.la.kb.push(b))}function zb(a,b,c){var d=K(a,{parent:!0}).node;a=Oa(a);if(!a||"."===a||".."===a)throw new I(28);var e=ub(d,a);if(e)throw new I(e);if(!d.Z.va)throw new I(63);return d.Z.va(d,a,b,c)}
function M(a){return zb(a,16895,0)}function Ab(a,b,c){"undefined"==typeof c&&(c=b,b=438);zb(a,b|8192,c)}function Bb(a,b){if(!Ra(a))throw new I(44);var c=K(b,{parent:!0}).node;if(!c)throw new I(44);b=Oa(b);var d=ub(c,b);if(d)throw new I(d);if(!c.Z.symlink)throw new I(63);c.Z.symlink(c,b,a)}function ob(a){a=K(a).node;if(!a)throw new I(44);if(!a.Z.readlink)throw new I(28);return Ra(pb(a.parent),a.Z.readlink(a))}
function Cb(a,b,c){if(""===a)throw new I(44);if("string"==typeof b){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof d)throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?("undefined"==typeof c?438:c)&4095|32768:0;if("object"==typeof a)var e=a;else{a=Ma(a);try{e=K(a,{Oa:!(b&131072)}).node}catch(f){}}d=!1;if(b&64)if(e){if(b&128)throw new I(20);}else e=zb(a,c,0),d=!0;if(!e)throw new I(44);8192===(e.mode&61440)&&(b&=-513);if(b&65536&&16384!==(e.mode&61440))throw new I(54);
if(!d&&(c=e?40960===(e.mode&61440)?32:16384===(e.mode&61440)&&("r"!==tb(b)||b&512)?31:rb(e,tb(b)):44))throw new I(c);if(b&512&&!d){c=e;c="string"==typeof c?K(c,{Oa:!0}).node:c;if(!c.Z.ka)throw new I(63);if(16384===(c.mode&61440))throw new I(31);if(32768!==(c.mode&61440))throw new I(28);if(d=rb(c,"w"))throw new I(d);c.Z.ka(c,{size:0,timestamp:Date.now()})}b&=-131713;e=wb({node:e,path:pb(e),flags:b,seekable:!0,position:0,aa:e.aa,ob:[],error:!1});e.aa.open&&e.aa.open(e);!m.logReadFiles||b&1||(Db||={},
a in Db||(Db[a]=1));return e}function Eb(a,b,c){if(null===a.fd)throw new I(8);if(!a.seekable||!a.aa.qa)throw new I(70);if(0!=c&&1!=c&&2!=c)throw new I(28);a.position=a.aa.qa(a,b,c);a.ob=[]}function Fb(){I||(I=function(a,b){this.name="ErrnoError";this.node=b;this.mb=function(c){this.pa=c};this.mb(a);this.message="FS error"},I.prototype=Error(),I.prototype.constructor=I,[44].forEach(a=>{fb[a]=new I(a);fb[a].stack="<generic error, no stack>"}))}var Gb;
function Hb(a,b,c){a=Ma("/dev/"+a);var d=hb(!!b,!!c);Ib||=64;var e=Ib++<<8|0;Ya(e,{open(f){f.seekable=!1},close(){c?.buffer?.length&&c(10)},read(f,g,k,l){for(var h=0,q=0;q<l;q++){try{var r=b()}catch(p){throw new I(29);}if(void 0===r&&0===h)throw new I(6);if(null===r||void 0===r)break;h++;g[k+q]=r}h&&(f.node.timestamp=Date.now());return h},write(f,g,k,l){for(var h=0;h<l;h++)try{c(g[k+h])}catch(q){throw new I(29);}l&&(f.node.timestamp=Date.now());return h}});Ab(a,d,e)}var Ib,N={},xb,Db,Jb=void 0;
function O(){var a=E[+Jb>>2];Jb+=4;return a}var Kb={},Lb=a=>{for(;a.length;){var b=a.pop();a.pop()(b)}};function Mb(a){return this.fromWireType(E[a>>2])}
var P={},Q={},Nb={},Ob,Pb=(a,b,c)=>{function d(k){k=c(k);if(k.length!==a.length)throw new Ob("Mismatched type converter count");for(var l=0;l<a.length;++l)R(a[l],k[l])}a.forEach(function(k){Nb[k]=b});var e=Array(b.length),f=[],g=0;b.forEach((k,l)=>{Q.hasOwnProperty(k)?e[l]=Q[k]:(f.push(k),P.hasOwnProperty(k)||(P[k]=[]),P[k].push(()=>{e[l]=Q[k];++g;g===f.length&&d(e)}))});0===f.length&&d(e)},Qb={},Rb=a=>{if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():
""+a},Sb,S=a=>{for(var b="";C[a];)b+=Sb[C[a++]];return b},T,Tb=a=>{throw new T(a);};function Ub(a,b,c={}){var d=b.name;if(!a)throw new T(`type "${d}" must have a positive integer typeid pointer`);if(Q.hasOwnProperty(a)){if(c.eb)return;throw new T(`Cannot register type '${d}' twice`);}Q[a]=b;delete Nb[a];P.hasOwnProperty(a)&&(b=P[a],delete P[a],b.forEach(e=>e()))}
function R(a,b,c={}){if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");Ub(a,b,c)}var Vb=(a,b,c)=>{switch(b){case 1:return c?d=>B[d>>0]:d=>C[d>>0];case 2:return c?d=>D[d>>1]:d=>pa[d>>1];case 4:return c?d=>E[d>>2]:d=>F[d>>2];case 8:return c?d=>ra[d>>3]:d=>sa[d>>3];default:throw new TypeError(`invalid integer width (${b}): ${a}`);}};function Wb(){this.ha=[void 0];this.Qa=[]}
var U=new Wb,Xb=a=>{a>=U.Y&&0===--U.get(a).Wa&&U.$a(a)},V=a=>{if(!a)throw new T("Cannot use deleted val. handle = "+a);return U.get(a).value},Yb=a=>{switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:return U.sa({Wa:1,value:a})}},Zb=(a,b)=>{switch(b){case 4:return function(c){return this.fromWireType(qa[c>>2])};case 8:return function(c){return this.fromWireType(ta[c>>3])};default:throw new TypeError(`invalid float width (${b}): ${a}`);}},$b=(a,b)=>Object.defineProperty(b,
"name",{value:a});function ac(a){for(var b=1;b<a.length;++b)if(null!==a[b]&&void 0===a[b].ea)return!0;return!1}function bc(a){var b=Function;if(!(b instanceof Function))throw new TypeError(`new_ called with constructor type ${typeof b} which is not a function`);var c=$b(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}
var cc=(a,b)=>{if(void 0===m[a].ja){var c=m[a];m[a]=function(){if(!m[a].ja.hasOwnProperty(arguments.length))throw new T(`Function '${b}' called with an invalid number of arguments (${arguments.length}) - expects one of (${m[a].ja})!`);return m[a].ja[arguments.length].apply(this,arguments)};m[a].ja=[];m[a].ja[c.ab]=c}},dc=(a,b,c)=>{if(m.hasOwnProperty(a)){if(void 0===c||void 0!==m[a].ja&&void 0!==m[a].ja[c])throw new T(`Cannot register public name '${a}' twice`);cc(a,a);if(m.hasOwnProperty(c))throw new T(`Cannot register multiple overloads of a function with the same number of arguments (${c})!`);
m[a].ja[c]=b}else m[a]=b,void 0!==c&&(m[a].vb=c)},gc=(a,b)=>{for(var c=[],d=0;d<a;d++)c.push(F[b+4*d>>2]);return c},hc,W=(a,b)=>{a=S(a);var c=hc.get(b);if("function"!=typeof c)throw new T(`unknown function pointer with signature ${a}: ${b}`);return c},ic,kc=a=>{a=jc(a);var b=S(a);X(a);return b},lc=(a,b)=>{function c(f){e[f]||Q[f]||(Nb[f]?Nb[f].forEach(c):(d.push(f),e[f]=!0))}var d=[],e={};b.forEach(c);throw new ic(`${a}: `+d.map(kc).join([", "]));},mc=a=>{a=a.trim();const b=a.indexOf("(");return-1!==
b?a.substr(0,b):a};function nc(a){return this.fromWireType(F[a>>2])}
var oc="undefined"!=typeof TextDecoder?new TextDecoder("utf-16le"):void 0,pc=(a,b)=>{var c=a>>1;for(var d=c+b/2;!(c>=d)&&pa[c];)++c;c<<=1;if(32<c-a&&oc)return oc.decode(C.subarray(a,c));c="";for(d=0;!(d>=b/2);++d){var e=D[a+2*d>>1];if(0==e)break;c+=String.fromCharCode(e)}return c},qc=(a,b,c)=>{c??=2147483647;if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)D[b>>1]=a.charCodeAt(e),b+=2;D[b>>1]=0;return b-d},rc=a=>2*a.length,sc=(a,b)=>{for(var c=0,d="";!(c>=b/4);){var e=
E[a+4*c>>2];if(0==e)break;++c;65536<=e?(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023)):d+=String.fromCharCode(e)}return d},tc=(a,b,c)=>{c??=2147483647;if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var f=a.charCodeAt(e);if(55296<=f&&57343>=f){var g=a.charCodeAt(++e);f=65536+((f&1023)<<10)|g&1023}E[b>>2]=f;b+=4;if(b+4>c)break}E[b>>2]=0;return b-d},uc=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b},vc=(a,b)=>{var c=Q[a];if(void 0===
c)throw a=b+" has unknown type "+kc(a),new T(a);return c},wc=(a,b,c)=>{var d=[];a=a.toWireType(d,c);d.length&&(F[b>>2]=Yb(d));return a},xc=[],yc={},zc=a=>{var b=yc[a];return void 0===b?S(a):b},Ac=a=>{var b=xc.length;xc.push(a);return b},Bc=(a,b)=>{for(var c=Array(a),d=0;d<a;++d)c[d]=vc(F[b+4*d>>2],"parameter "+d);return c},Cc=[],Dc={},Fc=()=>{if(!Ec){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||
"C").replace("-","_")+".UTF-8",_:da||"./this.program"},b;for(b in Dc)void 0===Dc[b]?delete a[b]:a[b]=Dc[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);Ec=c}return Ec},Ec;function sb(a,b,c,d){a||=this;this.parent=a;this.la=a.la;this.wa=null;this.id=lb++;this.name=b;this.mode=c;this.Z={};this.aa={};this.rdev=d}
Object.defineProperties(sb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}}});Fb();mb=Array(4096);yb(J,"/");M("/tmp");M("/home");M("/home/web_user");
(function(){M("/dev");Ya(259,{read:()=>0,write:(d,e,f,g)=>g});Ab("/dev/null",259);Xa(1280,$a);Xa(1536,bb);Ab("/dev/tty",1280);Ab("/dev/tty1",1536);var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(b=Qa(a).byteLength);return a[--b]};Hb("random",c);Hb("urandom",c);M("/dev/shm");M("/dev/shm/tmp")})();
(function(){M("/proc");var a=M("/proc/self");M("/proc/self/fd");yb({la(){var b=eb(a,"fd",16895,73);b.Z={lookup(c,d){var e=L(+d);c={parent:null,la:{Ta:"fake"},Z:{readlink:()=>e.path}};return c.parent=c}};return b}},"/proc/self/fd")})();Ob=m.InternalError=class extends Error{constructor(a){super(a);this.name="InternalError"}};for(var Gc=Array(256),Hc=0;256>Hc;++Hc)Gc[Hc]=String.fromCharCode(Hc);Sb=Gc;T=m.BindingError=class extends Error{constructor(a){super(a);this.name="BindingError"}};
Object.assign(Wb.prototype,{get(a){return this.ha[a]},has(a){return void 0!==this.ha[a]},sa(a){var b=this.Qa.pop()||this.ha.length;this.ha[b]=a;return b},$a(a){this.ha[a]=void 0;this.Qa.push(a)}});U.ha.push({value:void 0},{value:null},{value:!0},{value:!1});U.Y=U.ha.length;m.count_emval_handles=()=>{for(var a=0,b=U.Y;b<U.ha.length;++b)void 0!==U.ha[b]&&++a;return a};
ic=m.UnboundTypeError=((a,b)=>{var c=$b(b,function(d){this.name=b;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(a.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:`${this.name}: ${this.message}`};return c})(Error,"UnboundTypeError");
var Kc={r:function(a,b,c){Jb=c;try{var d=L(a);switch(b){case 0:var e=O();if(0>e)return-28;for(;kb[e];)e++;return wb(d,e).fd;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=O(),d.flags|=e,0;case 5:return e=O(),D[e+0>>1]=2,0;case 6:case 7:return 0;case 16:case 8:return-28;case 9:return E[Ic()>>2]=28,-1;default:return-28}}catch(f){if("undefined"==typeof N||"ErrnoError"!==f.name)throw f;return-f.pa}},E:function(a,b,c){Jb=c;try{var d=L(a);switch(b){case 21509:return d.tty?0:-59;case 21505:if(!d.tty)return-59;
if(d.tty.ma.gb){b=[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];var e=O();E[e>>2]=25856;E[e+4>>2]=5;E[e+8>>2]=191;E[e+12>>2]=35387;for(var f=0;32>f;f++)B[e+f+17>>0]=b[f]||0}return 0;case 21510:case 21511:case 21512:return d.tty?0:-59;case 21506:case 21507:case 21508:if(!d.tty)return-59;if(d.tty.ma.hb)for(e=O(),b=[],f=0;32>f;f++)b.push(B[e+f+17>>0]);return 0;case 21519:if(!d.tty)return-59;e=O();return E[e>>2]=0;case 21520:return d.tty?-28:-59;case 21531:e=O();if(!d.aa.fb)throw new I(59);
return d.aa.fb(d,b,e);case 21523:if(!d.tty)return-59;d.tty.ma.ib&&(f=[24,80],e=O(),D[e>>1]=f[0],D[e+2>>1]=f[1]);return 0;case 21524:return d.tty?0:-59;case 21515:return d.tty?0:-59;default:return-28}}catch(g){if("undefined"==typeof N||"ErrnoError"!==g.name)throw g;return-g.pa}},F:function(a,b,c,d){Jb=d;try{b=b?G(C,b):"";var e=b;if("/"===e.charAt(0))b=e;else{var f=-100===a?"/":L(a).path;if(0==e.length)throw new I(44);b=Ma(f+"/"+e)}var g=d?O():0;return Cb(b,c,g).fd}catch(k){if("undefined"==typeof N||
"ErrnoError"!==k.name)throw k;return-k.pa}},v:a=>{var b=Kb[a];delete Kb[a];var c=b.elements,d=c.length,e=c.map(k=>k.Ea).concat(c.map(k=>k.Ka)),f=b.Ga,g=b.Ha;Pb([a],e,function(k){c.forEach((l,h)=>{var q=k[h],r=l.Ca,p=l.Da,w=k[h+d],z=l.Ja,H=l.La;l.read=u=>q.fromWireType(r(p,u));l.write=(u,x)=>{var y=[];z(H,u,w.toWireType(y,x));Lb(y)}});return[{name:b.name,fromWireType:l=>{for(var h=Array(d),q=0;q<d;++q)h[q]=c[q].read(l);g(l);return h},toWireType:(l,h)=>{if(d!==h.length)throw new TypeError(`Incorrect number of tuple elements for ${b.name}: expected=${d}, actual=${h.length}`);
for(var q=f(),r=0;r<d;++r)c[r].write(q,h[r]);null!==l&&l.push(g,q);return q},argPackAdvance:8,readValueFromPointer:Mb,ea:g}]})},k:a=>{var b=Qb[a];delete Qb[a];var c=b.Ga,d=b.Ha,e=b.Na,f=e.map(g=>g.Ea).concat(e.map(g=>g.Ka));Pb([a],f,g=>{var k={};e.forEach((l,h)=>{var q=g[h],r=l.Ca,p=l.Da,w=g[h+e.length],z=l.Ja,H=l.La;k[l.cb]={read:u=>q.fromWireType(r(p,u)),write:(u,x)=>{var y=[];z(H,u,w.toWireType(y,x));Lb(y)}}});return[{name:b.name,fromWireType:l=>{var h={},q;for(q in k)h[q]=k[q].read(l);d(l);return h},
toWireType:(l,h)=>{for(var q in k)if(!(q in h))throw new TypeError(`Missing field: "${q}"`);var r=c();for(q in k)k[q].write(r,h[q]);null!==l&&l.push(d,r);return r},argPackAdvance:8,readValueFromPointer:Mb,ea:d}]})},t:(a,b,c,d,e)=>{b=S(b);var f=-1!=b.indexOf("u");f&&(e=(1n<<64n)-1n);R(a,{name:b,fromWireType:g=>g,toWireType:function(g,k){if("bigint"!=typeof k&&"number"!=typeof k)throw new TypeError(`Cannot convert "${Rb(k)}" to ${this.name}`);if(k<d||k>e)throw new TypeError(`Passing a number "${Rb(k)}" from JS side to C/C++ side to an argument of type "${b}", which is outside the valid range [${d}, ${e}]!`);
return k},argPackAdvance:8,readValueFromPointer:Vb(b,c,!f),ea:null})},H:(a,b,c,d)=>{b=S(b);R(a,{name:b,fromWireType:function(e){return!!e},toWireType:function(e,f){return f?c:d},argPackAdvance:8,readValueFromPointer:function(e){return this.fromWireType(C[e])},ea:null})},G:(a,b)=>{b=S(b);R(a,{name:b,fromWireType:c=>{var d=V(c);Xb(c);return d},toWireType:(c,d)=>Yb(d),argPackAdvance:8,readValueFromPointer:Mb,ea:null})},s:(a,b,c)=>{b=S(b);R(a,{name:b,fromWireType:d=>d,toWireType:(d,e)=>e,argPackAdvance:8,
readValueFromPointer:Zb(b,c),ea:null})},a:(a,b,c,d,e,f,g)=>{var k=gc(b,c);a=S(a);a=mc(a);e=W(d,e);dc(a,function(){lc(`Cannot call ${a} due to unbound types`,k)},b-1);Pb([],k,function(l){var h=[l[0],null].concat(l.slice(1));l=a;var q=a;var r=e,p=h.length;if(2>p)throw new T("argTypes array size mismatch! Must at least get return value and 'this' types!");var w=null!==h[1]&&!1,z=ac(h),H="void"!==h[0].name;r=[Tb,r,f,Lb,h[0],h[1]];for(var u=0;u<p-2;++u)r.push(h[u+2]);if(!z)for(u=w?1:2;u<h.length;++u)null!==
h[u].ea&&r.push(h[u].ea);z=ac(h);u=h.length;var x="",y="";for(p=0;p<u-2;++p)x+=(0!==p?", ":"")+"arg"+p,y+=(0!==p?", ":"")+"arg"+p+"Wired";x=`\n        return function (${x}) {\n        if (arguments.length !== ${u-2}) {\n          throwBindingError('function ${q} called with ' + arguments.length + ' arguments, expected ${u-2}');\n        }`;z&&(x+="var destructors = [];\n");var ec=z?"destructors":"null",ab="throwBindingError invoker fn runDestructors retType classParam".split(" ");w&&(x+="var thisWired = classParam['toWireType']("+
ec+", this);\n");for(p=0;p<u-2;++p)x+="var arg"+p+"Wired = argType"+p+"['toWireType']("+ec+", arg"+p+"); // "+h[p+2].name+"\n",ab.push("argType"+p);w&&(y="thisWired"+(0<y.length?", ":"")+y);x+=(H||g?"var rv = ":"")+"invoker(fn"+(0<y.length?", ":"")+y+");\n";if(z)x+="runDestructors(destructors);\n";else for(p=w?1:2;p<h.length;++p)w=1===p?"thisWired":"arg"+(p-2)+"Wired",null!==h[p].ea&&(x+=w+"_dtor("+w+"); // "+h[p].name+"\n",ab.push(w+"_dtor"));H&&(x+="var ret = retType['fromWireType'](rv);\nreturn ret;\n");
let [fc,Mc]=[ab,x+"}\n"];fc.push(Mc);h=bc(fc).apply(null,r);q=$b(q,h);h=b-1;if(!m.hasOwnProperty(l))throw new Ob("Replacing nonexistant public symbol");void 0!==m[l].ja&&void 0!==h?m[l].ja[h]=q:(m[l]=q,m[l].ab=h);return[]})},e:(a,b,c,d,e)=>{b=S(b);-1===e&&(e=4294967295);e=k=>k;if(0===d){var f=32-8*c;e=k=>k<<f>>>f}var g=b.includes("unsigned")?function(k,l){return l>>>0}:function(k,l){return l};R(a,{name:b,fromWireType:e,toWireType:g,argPackAdvance:8,readValueFromPointer:Vb(b,c,0!==d),ea:null})},b:(a,
b,c)=>{function d(f){return new e(B.buffer,F[f+4>>2],F[f>>2])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array,BigInt64Array,BigUint64Array][b];c=S(c);R(a,{name:c,fromWireType:d,argPackAdvance:8,readValueFromPointer:d},{eb:!0})},u:(a,b)=>{b=S(b);var c="std::string"===b;R(a,{name:b,fromWireType:function(d){var e=F[d>>2],f=d+4;if(c)for(var g=f,k=0;k<=e;++k){var l=f+k;if(k==e||0==C[l]){g=g?G(C,g,l-g):"";if(void 0===h)var h=g;else h+=String.fromCharCode(0),
h+=g;g=l+1}}else{h=Array(e);for(k=0;k<e;++k)h[k]=String.fromCharCode(C[f+k]);h=h.join("")}X(d);return h},toWireType:function(d,e){e instanceof ArrayBuffer&&(e=new Uint8Array(e));var f="string"==typeof e;if(!(f||e instanceof Uint8Array||e instanceof Uint8ClampedArray||e instanceof Int8Array))throw new T("Cannot pass non-string to std::string");var g=c&&f?Ua(e):e.length;var k=Jc(4+g+1),l=k+4;F[k>>2]=g;if(c&&f)Va(e,C,l,g+1);else if(f)for(f=0;f<g;++f){var h=e.charCodeAt(f);if(255<h)throw X(l),new T("String has UTF-16 code units that do not fit in 8 bits");
C[l+f]=h}else for(f=0;f<g;++f)C[l+f]=e[f];null!==d&&d.push(X,k);return k},argPackAdvance:8,readValueFromPointer:nc,ea(d){X(d)}})},j:(a,b,c)=>{c=S(c);if(2===b){var d=pc;var e=qc;var f=rc;var g=()=>pa;var k=1}else 4===b&&(d=sc,e=tc,f=uc,g=()=>F,k=2);R(a,{name:c,fromWireType:l=>{for(var h=F[l>>2],q=g(),r,p=l+4,w=0;w<=h;++w){var z=l+4+w*b;if(w==h||0==q[z>>k])p=d(p,z-p),void 0===r?r=p:(r+=String.fromCharCode(0),r+=p),p=z+b}X(l);return r},toWireType:(l,h)=>{if("string"!=typeof h)throw new T(`Cannot pass non-string to C++ string type ${c}`);
var q=f(h),r=Jc(4+q+b);F[r>>2]=q>>k;e(h,r+4,q+b);null!==l&&l.push(X,r);return r},argPackAdvance:8,readValueFromPointer:Mb,ea(l){X(l)}})},w:(a,b,c,d,e,f)=>{Kb[a]={name:S(b),Ga:W(c,d),Ha:W(e,f),elements:[]}},g:(a,b,c,d,e,f,g,k,l)=>{Kb[a].elements.push({Ea:b,Ca:W(c,d),Da:e,Ka:f,Ja:W(g,k),La:l})},l:(a,b,c,d,e,f)=>{Qb[a]={name:S(b),Ga:W(c,d),Ha:W(e,f),Na:[]}},h:(a,b,c,d,e,f,g,k,l,h)=>{Qb[a].Na.push({cb:S(b),Ea:c,Ca:W(d,e),Da:f,Ka:g,Ja:W(k,l),La:h})},J:(a,b)=>{b=S(b);R(a,{jb:!0,name:b,argPackAdvance:0,
fromWireType:()=>{},toWireType:()=>{}})},m:(a,b,c)=>{a=V(a);b=vc(b,"emval::as");return wc(b,c,a)},o:(a,b,c,d)=>{a=xc[a];b=V(b);return a(null,b,c,d)},K:(a,b,c,d,e)=>{a=xc[a];b=V(b);c=zc(c);return a(b,b[c],d,e)},I:Xb,i:(a,b,c)=>{b=Bc(a,b);var d=b.shift();a--;var e="return function (obj, func, destructorsRef, args) {\n",f=0,g=[];0===c&&g.push("obj");for(var k=["retType"],l=[d],h=0;h<a;++h)g.push("arg"+h),k.push("argType"+h),l.push(b[h]),e+=`  var arg${h} = argType${h}.readValueFromPointer(args${f?"+"+
f:""});\n`,f+=b[h].argPackAdvance;e+=`  var rv = ${1===c?"new func":"func.call"}(${g.join(", ")});\n`;for(h=0;h<a;++h)b[h].deleteObject&&(e+=`  argType${h}.deleteObject(arg${h});\n`);d.jb||(k.push("emval_returnValue"),l.push(wc),e+="  return emval_returnValue(retType, destructorsRef, rv);\n");k.push(e+"};\n");a=bc(k).apply(null,l);c=`methodCaller<(${b.map(q=>q.name).join(", ")}) => ${d.name}>`;return Ac($b(c,a))},n:(a,b)=>{a=V(a);b=V(b);return Yb(a[b])},q:a=>{4<a&&(U.get(a).Wa+=1)},L:a=>Yb(zc(a)),
x:a=>{var b=V(a);Lb(b);Xb(a)},f:(a,b)=>{a=vc(a,"_emval_take_value");a=a.readValueFromPointer(b);return Yb(a)},c:()=>{na("")},d:(a,b,c)=>{Cc.length=0;for(var d;d=C[b++];){var e=105!=d;e&=112!=d;c+=e&&c%8?4:0;Cc.push(112==d?F[c>>2]:106==d?ra[c>>3]:105==d?E[c>>2]:ta[c>>3]);c+=e?8:4}return Ka[a].apply(null,Cc)},y:a=>{var b=C.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);var e=Math;d=Math.max(a,d);a:{e=(e.min.call(e,2147483648,d+(65536-d%65536)%
65536)-A.buffer.byteLength+65535)/65536;try{A.grow(e);ua();var f=1;break a}catch(g){}f=void 0}if(f)return!0}return!1},A:(a,b)=>{var c=0;Fc().forEach((d,e)=>{var f=b+c;e=F[a+4*e>>2]=f;for(f=0;f<d.length;++f)B[e++>>0]=d.charCodeAt(f);B[e>>0]=0;c+=d.length+1});return 0},B:(a,b)=>{var c=Fc();F[a>>2]=c.length;var d=0;c.forEach(e=>d+=e.length+1);F[b>>2]=d;return 0},p:function(a){try{var b=L(a);if(null===b.fd)throw new I(8);b.Ba&&(b.Ba=null);try{b.aa.close&&b.aa.close(b)}catch(c){throw c;}finally{kb[b.fd]=
null}b.fd=null;return 0}catch(c){if("undefined"==typeof N||"ErrnoError"!==c.name)throw c;return c.pa}},D:function(a,b,c,d){try{a:{var e=L(a);a=b;for(var f,g=b=0;g<c;g++){var k=F[a>>2],l=F[a+4>>2];a+=8;var h=e,q=k,r=l,p=f,w=B;if(0>r||0>p)throw new I(28);if(null===h.fd)throw new I(8);if(1===(h.flags&2097155))throw new I(8);if(16384===(h.node.mode&61440))throw new I(31);if(!h.aa.read)throw new I(28);var z="undefined"!=typeof p;if(!z)p=h.position;else if(!h.seekable)throw new I(70);var H=h.aa.read(h,
w,q,r,p);z||(h.position+=H);var u=H;if(0>u){var x=-1;break a}b+=u;if(u<l)break;"undefined"!==typeof f&&(f+=u)}x=b}F[d>>2]=x;return 0}catch(y){if("undefined"==typeof N||"ErrnoError"!==y.name)throw y;return y.pa}},z:function(a,b,c,d){b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);try{if(isNaN(b))return 61;var e=L(a);Eb(e,b,c);ra[d>>3]=BigInt(e.position);e.Ba&&0===b&&0===c&&(e.Ba=null);return 0}catch(f){if("undefined"==typeof N||"ErrnoError"!==f.name)throw f;return f.pa}},C:function(a,b,c,d){try{a:{var e=
L(a);a=b;for(var f,g=b=0;g<c;g++){var k=F[a>>2],l=F[a+4>>2];a+=8;var h=e,q=k,r=l,p=f,w=B;if(0>r||0>p)throw new I(28);if(null===h.fd)throw new I(8);if(0===(h.flags&2097155))throw new I(8);if(16384===(h.node.mode&61440))throw new I(31);if(!h.aa.write)throw new I(28);h.seekable&&h.flags&1024&&Eb(h,0,2);var z="undefined"!=typeof p;if(!z)p=h.position;else if(!h.seekable)throw new I(70);var H=h.aa.write(h,w,q,r,p,void 0);z||(h.position+=H);var u=H;if(0>u){var x=-1;break a}b+=u;"undefined"!==typeof f&&(f+=
u)}x=b}F[d>>2]=x;return 0}catch(y){if("undefined"==typeof N||"ErrnoError"!==y.name)throw y;return y.pa}}},Z=function(){var a={a:Kc};ya++;Ga(a,function(b){Z=b.instance.exports;A=Z.M;m.wasmMemory=A;ua();hc=Z.X;wa.unshift(Z.N);ya--;0==ya&&(null!==za&&(clearInterval(za),za=null),Aa&&(b=Aa,Aa=null,b()))}).catch(ba);return{}}(),Ic=()=>(Ic=Z.O)(),Ha=m._ma_device__on_notification_unlocked=a=>(Ha=m._ma_device__on_notification_unlocked=Z.P)(a);
m._ma_malloc_emscripten=(a,b)=>(m._ma_malloc_emscripten=Z.Q)(a,b);m._ma_free_emscripten=(a,b)=>(m._ma_free_emscripten=Z.R)(a,b);var Ia=m._ma_device_process_pcm_frames_capture__webaudio=(a,b,c)=>(Ia=m._ma_device_process_pcm_frames_capture__webaudio=Z.S)(a,b,c),Ja=m._ma_device_process_pcm_frames_playback__webaudio=(a,b,c)=>(Ja=m._ma_device_process_pcm_frames_playback__webaudio=Z.T)(a,b,c),Jc=a=>(Jc=Z.U)(a),X=a=>(X=Z.V)(a),jc=a=>(jc=Z.W)(a);m.wasmMemory=A;var Lc;Aa=function Nc(){Lc||Oc();Lc||(Aa=Nc)};
function Oc(){if(!(0<ya)){for(;0<va.length;)va.shift()(m);if(!(0<ya||Lc||(Lc=!0,m.calledRun=!0,oa))){m.noFSInit||Gb||(Gb=!0,Fb(),m.stdin=m.stdin,m.stdout=m.stdout,m.stderr=m.stderr,m.stdin?Hb("stdin",m.stdin):Bb("/dev/tty","/dev/stdin"),m.stdout?Hb("stdout",null,m.stdout):Bb("/dev/tty","/dev/stdout"),m.stderr?Hb("stderr",null,m.stderr):Bb("/dev/tty1","/dev/stderr"),Cb("/dev/stdin",0),Cb("/dev/stdout",1),Cb("/dev/stderr",1));for(nb=!1;0<wa.length;)wa.shift()(m);aa(m);if(m.onRuntimeInitialized)m.onRuntimeInitialized();
for(;0<xa.length;)xa.shift()(m)}}}Oc();


  return moduleArg.ready
}
);
})();
;
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = RiveText;
else if (typeof define === 'function' && define['amd'])
  define([], () => RiveText);
